// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go_course_pb/go_course.proto

package go_course_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=firstNumber,proto3" json:"firstNumber,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=secondNumber,proto3" json:"secondNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9190394901c994, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	Sum                  int64    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9190394901c994, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type PrimeNumberRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberRequest) Reset()         { *m = PrimeNumberRequest{} }
func (m *PrimeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberRequest) ProtoMessage()    {}
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9190394901c994, []int{2}
}

func (m *PrimeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberRequest.Unmarshal(m, b)
}
func (m *PrimeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberRequest.Merge(m, src)
}
func (m *PrimeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberRequest.Size(m)
}
func (m *PrimeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberRequest proto.InternalMessageInfo

func (m *PrimeNumberRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberResponse struct {
	Divisor              int32    `protobuf:"varint,1,opt,name=divisor,proto3" json:"divisor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberResponse) Reset()         { *m = PrimeNumberResponse{} }
func (m *PrimeNumberResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberResponse) ProtoMessage()    {}
func (*PrimeNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9190394901c994, []int{3}
}

func (m *PrimeNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberResponse.Unmarshal(m, b)
}
func (m *PrimeNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberResponse.Merge(m, src)
}
func (m *PrimeNumberResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberResponse.Size(m)
}
func (m *PrimeNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberResponse proto.InternalMessageInfo

func (m *PrimeNumberResponse) GetDivisor() int32 {
	if m != nil {
		return m.Divisor
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "sum.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "sum.SumResponse")
	proto.RegisterType((*PrimeNumberRequest)(nil), "sum.PrimeNumberRequest")
	proto.RegisterType((*PrimeNumberResponse)(nil), "sum.PrimeNumberResponse")
}

func init() { proto.RegisterFile("go_course_pb/go_course.proto", fileDescriptor_eb9190394901c994) }

var fileDescriptor_eb9190394901c994 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xc1, 0x0a, 0x93, 0x62, 0xcb, 0x08, 0x1a, 0x8a, 0x60, 0xd9, 0x93, 0x88, 0xa4,
	0xa2, 0x6f, 0xa0, 0x82, 0x37, 0x91, 0xe4, 0xe6, 0xa5, 0x90, 0x74, 0x94, 0x3d, 0x6c, 0x26, 0xee,
	0x64, 0xfb, 0x02, 0xbe, 0xb8, 0xb8, 0xcd, 0xda, 0x2d, 0x39, 0xce, 0xbf, 0x1f, 0xff, 0xb7, 0x33,
	0x70, 0xf5, 0xc5, 0xeb, 0x86, 0x9d, 0x15, 0x5a, 0x77, 0xf5, 0xea, 0x7f, 0x28, 0x3a, 0xcb, 0x3d,
	0x63, 0x2a, 0xce, 0xa8, 0x12, 0xa0, 0x72, 0xa6, 0xa4, 0x6f, 0x47, 0xd2, 0xe3, 0x12, 0xb2, 0x4f,
	0x6d, 0xa5, 0x7f, 0x73, 0xa6, 0x26, 0x9b, 0x27, 0xcb, 0xe4, 0xe6, 0xa4, 0x8c, 0x23, 0x54, 0x30,
	0x15, 0x6a, 0xb8, 0xdd, 0x0c, 0xc8, 0xb1, 0x47, 0x0e, 0x32, 0x75, 0x0d, 0x99, 0xef, 0x94, 0x8e,
	0x5b, 0x21, 0x9c, 0xc3, 0x9f, 0xc9, 0x97, 0xa5, 0xa5, 0x97, 0xde, 0x01, 0xbe, 0x5b, 0x6d, 0x68,
	0xc7, 0x07, 0xf9, 0x05, 0x4c, 0xda, 0xd8, 0x3b, 0x4c, 0x6a, 0x05, 0xe7, 0x07, 0xf4, 0x50, 0x9b,
	0xc3, 0xe9, 0x46, 0x6f, 0xb5, 0x70, 0xe0, 0xc3, 0xf8, 0xf0, 0x93, 0xc0, 0xec, 0x95, 0x9f, 0xfd,
	0xae, 0x15, 0xd9, 0xad, 0x6e, 0x08, 0x6f, 0x21, 0xad, 0x9c, 0xc1, 0x59, 0x21, 0xce, 0x14, 0xfb,
	0x8d, 0x17, 0xf3, 0x7d, 0xb0, 0xeb, 0x55, 0x47, 0xf8, 0x02, 0x59, 0x24, 0xc4, 0x4b, 0x8f, 0x8c,
	0x3f, 0xbc, 0xc8, 0xc7, 0x0f, 0xa1, 0xe3, 0x3e, 0x79, 0x3a, 0xfb, 0x98, 0xc6, 0xe7, 0xaf, 0x27,
	0xfe, 0xea, 0x8f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0x1f, 0x79, 0xe9, 0x95, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoCourseServiceClient is the client API for GoCourseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoCourseServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeNumber(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (GoCourseService_PrimeNumberClient, error)
}

type goCourseServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoCourseServiceClient(cc *grpc.ClientConn) GoCourseServiceClient {
	return &goCourseServiceClient{cc}
}

func (c *goCourseServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/sum.GoCourseService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCourseServiceClient) PrimeNumber(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (GoCourseService_PrimeNumberClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GoCourseService_serviceDesc.Streams[0], "/sum.GoCourseService/PrimeNumber", opts...)
	if err != nil {
		return nil, err
	}
	x := &goCourseServicePrimeNumberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoCourseService_PrimeNumberClient interface {
	Recv() (*PrimeNumberResponse, error)
	grpc.ClientStream
}

type goCourseServicePrimeNumberClient struct {
	grpc.ClientStream
}

func (x *goCourseServicePrimeNumberClient) Recv() (*PrimeNumberResponse, error) {
	m := new(PrimeNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoCourseServiceServer is the server API for GoCourseService service.
type GoCourseServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimeNumber(*PrimeNumberRequest, GoCourseService_PrimeNumberServer) error
}

// UnimplementedGoCourseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGoCourseServiceServer struct {
}

func (*UnimplementedGoCourseServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedGoCourseServiceServer) PrimeNumber(req *PrimeNumberRequest, srv GoCourseService_PrimeNumberServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumber not implemented")
}

func RegisterGoCourseServiceServer(s *grpc.Server, srv GoCourseServiceServer) {
	s.RegisterService(&_GoCourseService_serviceDesc, srv)
}

func _GoCourseService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCourseServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sum.GoCourseService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCourseServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCourseService_PrimeNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoCourseServiceServer).PrimeNumber(m, &goCourseServicePrimeNumberServer{stream})
}

type GoCourseService_PrimeNumberServer interface {
	Send(*PrimeNumberResponse) error
	grpc.ServerStream
}

type goCourseServicePrimeNumberServer struct {
	grpc.ServerStream
}

func (x *goCourseServicePrimeNumberServer) Send(m *PrimeNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GoCourseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sum.GoCourseService",
	HandlerType: (*GoCourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _GoCourseService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumber",
			Handler:       _GoCourseService_PrimeNumber_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "go_course_pb/go_course.proto",
}
